// Code generated by MockGen. DO NOT EDIT.
// Source: backup_master/internal/repository (interfaces: BackupRepositoryInterface)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/backup_repo_mock.go -package=mocks backup_master/internal/repository BackupRepositoryInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	model "backup_master/internal/model"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockBackupRepositoryInterface is a mock of BackupRepositoryInterface interface.
type MockBackupRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBackupRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockBackupRepositoryInterfaceMockRecorder is the mock recorder for MockBackupRepositoryInterface.
type MockBackupRepositoryInterfaceMockRecorder struct {
	mock *MockBackupRepositoryInterface
}

// NewMockBackupRepositoryInterface creates a new mock instance.
func NewMockBackupRepositoryInterface(ctrl *gomock.Controller) *MockBackupRepositoryInterface {
	mock := &MockBackupRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockBackupRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackupRepositoryInterface) EXPECT() *MockBackupRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CountAll mocks base method.
func (m *MockBackupRepositoryInterface) CountAll() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAll")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountAll indicates an expected call of CountAll.
func (mr *MockBackupRepositoryInterfaceMockRecorder) CountAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAll", reflect.TypeOf((*MockBackupRepositoryInterface)(nil).CountAll))
}

// CountByStatus mocks base method.
func (m *MockBackupRepositoryInterface) CountByStatus(status string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByStatus", status)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByStatus indicates an expected call of CountByStatus.
func (mr *MockBackupRepositoryInterfaceMockRecorder) CountByStatus(status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByStatus", reflect.TypeOf((*MockBackupRepositoryInterface)(nil).CountByStatus), status)
}

// Create mocks base method.
func (m *MockBackupRepositoryInterface) Create(b *model.Backup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", b)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBackupRepositoryInterfaceMockRecorder) Create(b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBackupRepositoryInterface)(nil).Create), b)
}

// GetAll mocks base method.
func (m *MockBackupRepositoryInterface) GetAll() ([]model.Backup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]model.Backup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockBackupRepositoryInterfaceMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockBackupRepositoryInterface)(nil).GetAll))
}

// GetByID mocks base method.
func (m *MockBackupRepositoryInterface) GetByID(id int64) (*model.Backup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*model.Backup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockBackupRepositoryInterfaceMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockBackupRepositoryInterface)(nil).GetByID), id)
}

// GetHistory mocks base method.
func (m *MockBackupRepositoryInterface) GetHistory(limit int, statusFilter string, dateFilter *time.Time, id *int64) ([]model.BackupWithTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistory", limit, statusFilter, dateFilter, id)
	ret0, _ := ret[0].([]model.BackupWithTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistory indicates an expected call of GetHistory.
func (mr *MockBackupRepositoryInterfaceMockRecorder) GetHistory(limit, statusFilter, dateFilter, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistory", reflect.TypeOf((*MockBackupRepositoryInterface)(nil).GetHistory), limit, statusFilter, dateFilter, id)
}

// GetLast mocks base method.
func (m *MockBackupRepositoryInterface) GetLast(limit int) ([]model.Backup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLast", limit)
	ret0, _ := ret[0].([]model.Backup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLast indicates an expected call of GetLast.
func (mr *MockBackupRepositoryInterfaceMockRecorder) GetLast(limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLast", reflect.TypeOf((*MockBackupRepositoryInterface)(nil).GetLast), limit)
}
