// Code generated by MockGen. DO NOT EDIT.
// Source: backup_master/internal/repository (interfaces: SettingsRepositoryInterface)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/settings_repo_mock.go -package=mocks backup_master/internal/repository SettingsRepositoryInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	model "backup_master/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSettingsRepositoryInterface is a mock of SettingsRepositoryInterface interface.
type MockSettingsRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSettingsRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockSettingsRepositoryInterfaceMockRecorder is the mock recorder for MockSettingsRepositoryInterface.
type MockSettingsRepositoryInterfaceMockRecorder struct {
	mock *MockSettingsRepositoryInterface
}

// NewMockSettingsRepositoryInterface creates a new mock instance.
func NewMockSettingsRepositoryInterface(ctrl *gomock.Controller) *MockSettingsRepositoryInterface {
	mock := &MockSettingsRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockSettingsRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSettingsRepositoryInterface) EXPECT() *MockSettingsRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockSettingsRepositoryInterface) Get() (*model.AppSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(*model.AppSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSettingsRepositoryInterfaceMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSettingsRepositoryInterface)(nil).Get))
}

// Save mocks base method.
func (m *MockSettingsRepositoryInterface) Save(s *model.AppSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockSettingsRepositoryInterfaceMockRecorder) Save(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSettingsRepositoryInterface)(nil).Save), s)
}

// UpdateBackupSettings mocks base method.
func (m *MockSettingsRepositoryInterface) UpdateBackupSettings(path string, maxBytes int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBackupSettings", path, maxBytes)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBackupSettings indicates an expected call of UpdateBackupSettings.
func (mr *MockSettingsRepositoryInterfaceMockRecorder) UpdateBackupSettings(path, maxBytes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBackupSettings", reflect.TypeOf((*MockSettingsRepositoryInterface)(nil).UpdateBackupSettings), path, maxBytes)
}

// UpdateTheme mocks base method.
func (m *MockSettingsRepositoryInterface) UpdateTheme(mode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTheme", mode)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTheme indicates an expected call of UpdateTheme.
func (mr *MockSettingsRepositoryInterfaceMockRecorder) UpdateTheme(mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTheme", reflect.TypeOf((*MockSettingsRepositoryInterface)(nil).UpdateTheme), mode)
}
