// Code generated by MockGen. DO NOT EDIT.
// Source: backup_master/internal/repository (interfaces: TaskRepositoryInterface)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/task_repo_mock.go -package=mocks backup_master/internal/repository TaskRepositoryInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	model "backup_master/internal/model"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockTaskRepositoryInterface is a mock of TaskRepositoryInterface interface.
type MockTaskRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTaskRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockTaskRepositoryInterfaceMockRecorder is the mock recorder for MockTaskRepositoryInterface.
type MockTaskRepositoryInterfaceMockRecorder struct {
	mock *MockTaskRepositoryInterface
}

// NewMockTaskRepositoryInterface creates a new mock instance.
func NewMockTaskRepositoryInterface(ctrl *gomock.Controller) *MockTaskRepositoryInterface {
	mock := &MockTaskRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockTaskRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskRepositoryInterface) EXPECT() *MockTaskRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CountUpcoming mocks base method.
func (m *MockTaskRepositoryInterface) CountUpcoming(from, to time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUpcoming", from, to)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUpcoming indicates an expected call of CountUpcoming.
func (mr *MockTaskRepositoryInterfaceMockRecorder) CountUpcoming(from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUpcoming", reflect.TypeOf((*MockTaskRepositoryInterface)(nil).CountUpcoming), from, to)
}

// Create mocks base method.
func (m *MockTaskRepositoryInterface) Create(task *model.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", task)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTaskRepositoryInterfaceMockRecorder) Create(task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTaskRepositoryInterface)(nil).Create), task)
}

// Delete mocks base method.
func (m *MockTaskRepositoryInterface) Delete(taskID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTaskRepositoryInterfaceMockRecorder) Delete(taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTaskRepositoryInterface)(nil).Delete), taskID)
}

// GetAll mocks base method.
func (m *MockTaskRepositoryInterface) GetAll() ([]model.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]model.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockTaskRepositoryInterfaceMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockTaskRepositoryInterface)(nil).GetAll))
}

// GetEnabled mocks base method.
func (m *MockTaskRepositoryInterface) GetEnabled() ([]model.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnabled")
	ret0, _ := ret[0].([]model.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnabled indicates an expected call of GetEnabled.
func (mr *MockTaskRepositoryInterfaceMockRecorder) GetEnabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnabled", reflect.TypeOf((*MockTaskRepositoryInterface)(nil).GetEnabled))
}

// GetUpcoming mocks base method.
func (m *MockTaskRepositoryInterface) GetUpcoming(limit int) ([]model.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpcoming", limit)
	ret0, _ := ret[0].([]model.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUpcoming indicates an expected call of GetUpcoming.
func (mr *MockTaskRepositoryInterfaceMockRecorder) GetUpcoming(limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpcoming", reflect.TypeOf((*MockTaskRepositoryInterface)(nil).GetUpcoming), limit)
}

// SetEnabled mocks base method.
func (m *MockTaskRepositoryInterface) SetEnabled(taskID int64, enabled bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEnabled", taskID, enabled)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetEnabled indicates an expected call of SetEnabled.
func (mr *MockTaskRepositoryInterfaceMockRecorder) SetEnabled(taskID, enabled any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEnabled", reflect.TypeOf((*MockTaskRepositoryInterface)(nil).SetEnabled), taskID, enabled)
}

// Update mocks base method.
func (m *MockTaskRepositoryInterface) Update(task *model.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", task)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTaskRepositoryInterfaceMockRecorder) Update(task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTaskRepositoryInterface)(nil).Update), task)
}
