// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	model "backup_master/internal/model"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// BackupRepositoryInterface is an autogenerated mock type for the BackupRepositoryInterface type
type BackupRepositoryInterface struct {
	mock.Mock
}

// CountAll provides a mock function with no fields
func (_m *BackupRepositoryInterface) CountAll() (int, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CountAll")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func() (int, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountByStatus provides a mock function with given fields: status
func (_m *BackupRepositoryInterface) CountByStatus(status string) (int, error) {
	ret := _m.Called(status)

	if len(ret) == 0 {
		panic("no return value specified for CountByStatus")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int, error)); ok {
		return rf(status)
	}
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(status)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: b
func (_m *BackupRepositoryInterface) Create(b *model.Backup) error {
	ret := _m.Called(b)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Backup) error); ok {
		r0 = rf(b)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with no fields
func (_m *BackupRepositoryInterface) GetAll() ([]model.Backup, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []model.Backup
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]model.Backup, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []model.Backup); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Backup)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *BackupRepositoryInterface) GetByID(id int64) (*model.Backup, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Backup
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (*model.Backup, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int64) *model.Backup); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Backup)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetHistory provides a mock function with given fields: limit, statusFilter, dateFilter, id
func (_m *BackupRepositoryInterface) GetHistory(limit int, statusFilter string, dateFilter *time.Time, id *int64) ([]model.BackupWithTask, error) {
	ret := _m.Called(limit, statusFilter, dateFilter, id)

	if len(ret) == 0 {
		panic("no return value specified for GetHistory")
	}

	var r0 []model.BackupWithTask
	var r1 error
	if rf, ok := ret.Get(0).(func(int, string, *time.Time, *int64) ([]model.BackupWithTask, error)); ok {
		return rf(limit, statusFilter, dateFilter, id)
	}
	if rf, ok := ret.Get(0).(func(int, string, *time.Time, *int64) []model.BackupWithTask); ok {
		r0 = rf(limit, statusFilter, dateFilter, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.BackupWithTask)
		}
	}

	if rf, ok := ret.Get(1).(func(int, string, *time.Time, *int64) error); ok {
		r1 = rf(limit, statusFilter, dateFilter, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLast provides a mock function with given fields: limit
func (_m *BackupRepositoryInterface) GetLast(limit int) ([]model.Backup, error) {
	ret := _m.Called(limit)

	if len(ret) == 0 {
		panic("no return value specified for GetLast")
	}

	var r0 []model.Backup
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]model.Backup, error)); ok {
		return rf(limit)
	}
	if rf, ok := ret.Get(0).(func(int) []model.Backup); ok {
		r0 = rf(limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Backup)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBackupRepositoryInterface creates a new instance of BackupRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBackupRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *BackupRepositoryInterface {
	mock := &BackupRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
