// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	model "backup_master/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// SettingsRepositoryInterface is an autogenerated mock type for the SettingsRepositoryInterface type
type SettingsRepositoryInterface struct {
	mock.Mock
}

// Get provides a mock function with no fields
func (_m *SettingsRepositoryInterface) Get() (*model.AppSettings, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.AppSettings
	var r1 error
	if rf, ok := ret.Get(0).(func() (*model.AppSettings, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *model.AppSettings); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AppSettings)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: s
func (_m *SettingsRepositoryInterface) Save(s *model.AppSettings) error {
	ret := _m.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.AppSettings) error); ok {
		r0 = rf(s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateBackupSettings provides a mock function with given fields: path, maxBytes
func (_m *SettingsRepositoryInterface) UpdateBackupSettings(path string, maxBytes int64) error {
	ret := _m.Called(path, maxBytes)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBackupSettings")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int64) error); ok {
		r0 = rf(path, maxBytes)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTheme provides a mock function with given fields: mode
func (_m *SettingsRepositoryInterface) UpdateTheme(mode string) error {
	ret := _m.Called(mode)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTheme")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(mode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSettingsRepositoryInterface creates a new instance of SettingsRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSettingsRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *SettingsRepositoryInterface {
	mock := &SettingsRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
