// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	model "backup_master/internal/model"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// TaskRepositoryInterface is an autogenerated mock type for the TaskRepositoryInterface type
type TaskRepositoryInterface struct {
	mock.Mock
}

// CountUpcoming provides a mock function with given fields: from, to
func (_m *TaskRepositoryInterface) CountUpcoming(from time.Time, to time.Time) (int, error) {
	ret := _m.Called(from, to)

	if len(ret) == 0 {
		panic("no return value specified for CountUpcoming")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(time.Time, time.Time) (int, error)); ok {
		return rf(from, to)
	}
	if rf, ok := ret.Get(0).(func(time.Time, time.Time) int); ok {
		r0 = rf(from, to)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(time.Time, time.Time) error); ok {
		r1 = rf(from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: task
func (_m *TaskRepositoryInterface) Create(task *model.Task) error {
	ret := _m.Called(task)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Task) error); ok {
		r0 = rf(task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: taskID
func (_m *TaskRepositoryInterface) Delete(taskID int64) error {
	ret := _m.Called(taskID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(taskID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with no fields
func (_m *TaskRepositoryInterface) GetAll() ([]model.Task, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]model.Task, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []model.Task); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Task)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEnabled provides a mock function with no fields
func (_m *TaskRepositoryInterface) GetEnabled() ([]model.Task, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEnabled")
	}

	var r0 []model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]model.Task, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []model.Task); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Task)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUpcoming provides a mock function with given fields: limit
func (_m *TaskRepositoryInterface) GetUpcoming(limit int) ([]model.Task, error) {
	ret := _m.Called(limit)

	if len(ret) == 0 {
		panic("no return value specified for GetUpcoming")
	}

	var r0 []model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]model.Task, error)); ok {
		return rf(limit)
	}
	if rf, ok := ret.Get(0).(func(int) []model.Task); ok {
		r0 = rf(limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetEnabled provides a mock function with given fields: taskID, enabled
func (_m *TaskRepositoryInterface) SetEnabled(taskID int64, enabled bool) error {
	ret := _m.Called(taskID, enabled)

	if len(ret) == 0 {
		panic("no return value specified for SetEnabled")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, bool) error); ok {
		r0 = rf(taskID, enabled)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: task
func (_m *TaskRepositoryInterface) Update(task *model.Task) error {
	ret := _m.Called(task)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Task) error); ok {
		r0 = rf(task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTaskRepositoryInterface creates a new instance of TaskRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskRepositoryInterface {
	mock := &TaskRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
